USE leapmaster21_test ;

DROP TABLE IF EXISTS book_author ;
DROP TABLE IF EXISTS Author ;
DROP TABLE IF EXISTS Book ;

CREATE TABLE IF NOT EXISTS Author ( authorid INT NOT NULL AUTO_INCREMENT, firstname VARCHAR(45) NOT NULL, lastname VARCHAR(45) NOT NULL, PRIMARY KEY (authorid));
CREATE TABLE IF NOT EXISTS Book ( isbn INT NOT NULL AUTO_INCREMENT, author VARCHAR(45) NOT NULL, price DOUBLE NOT NULL, title VARCHAR(45) NOT NULL, PRIMARY KEY (ISBN));
CREATE TABLE IF NOT EXISTS book_author ( Book INT REFERENCES BOOK(isbn), Author INT REFERENCES AUTHOR(authorid), PRIMARY KEY(Book, Author));
